In [3]:
import numpy as np

# Numpy is Numerical Python.
*It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

# Numpy Functions

In [4]:
array1 = np.array([[1,2,3,4],[5,6,7,8]])
array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### np.zeros

In [5]:
array2 = np.zeros((4,3) , dtype=int)   # Default dtype = float
array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### np.ones

In [6]:
array3 = np.ones((2,3) , dtype=int)
array3

array([[1, 1, 1],
       [1, 1, 1]])

### np.arange

In [7]:
array4 = np.arange(6,20,2)
array4

array([ 6,  8, 10, 12, 14, 16, 18])

### random

In [10]:
array6 = np.random.randint(0,27,size=(3,4))
print(array6)

[[14 22  1  4]
 [22 12  9 17]
 [19 14 19 10]]


### np.full

In [13]:
array7 = np.full((3,2,2),6)
print(array7)

[[[6 6]
  [6 6]]

 [[6 6]
  [6 6]]

 [[6 6]
  [6 6]]]


In [14]:
a = np.random.randint(1,5,(2,4))
a

array([[1, 3, 4, 4],
       [2, 1, 3, 3]])

In [15]:
b = np.random.randint(5,10,(2,4))
b

array([[5, 7, 9, 9],
       [9, 5, 8, 5]])

### divide

In [16]:
divide = np.divide(10,2)
divide

5.0

### multiplication

In [17]:
multiply = np.multiply(186, 200)
multiply

37200

### Aggregation Operations


In [18]:
data = np.random.randint(1,10,(2,4))
data

array([[3, 1, 2, 4],
       [3, 5, 6, 3]])

### add

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.add(a, b)
c


array([5, 7, 9])

### subtract

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.subtract(a, b)
c

array([-3, -3, -3])

# Numpy array attributes
### ndarray.shape
*This returns a tuple consisting of array dimensions.

In [28]:
array_1 = np.array([[1,2,3],[4,5,6]])
print(array_1.shape)

(2, 3)


In [29]:
array_2 = np.array([[[1,2,3],[4,5,6]],
                       [[1,3,3],[4,5,6]],
                       [[1,3,3],[4,5,6]],
                       [[1,3,3],[4,5,6]]])
print(array_2.shape)

(4, 2, 3)


### ndarray.ndim
*This returns the number of array dimensions.

In [30]:
array_3 = np.array([[1,2,3],[4,5,6]])
print(f"The dimension of array_3: ",array_3.ndim)

The dimension of array_3:  2


### ndarray.size
*This returns the total number of elements in the array

array_4 = np.array([[1,2,3],[4,5,6]])
print(f"The total number of elements in array_4 =  {array_4.size}")

### ndarray.dtype
*This returns the data type of the array

array_5 = np.array([1,2,3,4,5])
print(array_5.dtype)

### ndarray.astype
*This changes the data type of an array.

In [34]:
array_7 = np.array([2,3,4])
array_7_ = array_7.astype('float64')
print(array_7_.dtype)
print(array_7_)

float64
[2. 3. 4.]


# Array Manipulation

### np.transpose(array)

In [36]:
array_8 = np.array(np.random.randint(1,6,(8,2)))
array_8

array([[2, 2],
       [2, 2],
       [4, 1],
       [3, 5],
       [5, 5],
       [5, 3],
       [3, 3],
       [3, 3]])

In [37]:
transpose_arr = np.transpose(array_8)
transpose_arr


array([[2, 2, 4, 3, 5, 5, 3, 3],
       [2, 2, 1, 5, 5, 3, 3, 3]])

### np.reshape(array,shape)
*To Change shape of an array

In [38]:
array_9 = np.array(np.random.randint(1,6,(6,2)))
array_9

array([[2, 1],
       [5, 3],
       [3, 1],
       [5, 1],
       [4, 2],
       [1, 4]])

# flatten

In [39]:
array_10 = np.array(np.random.randint(1,6,(6,2)))
array_10

array([[2, 5],
       [3, 5],
       [1, 5],
       [1, 3],
       [1, 1],
       [1, 4]])

In [40]:
array_10.flatten()

array([2, 5, 3, 5, 1, 5, 1, 3, 1, 1, 1, 4])